version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2345:80'
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: 'mariadb'
    restart: always
    environment:
      MYSQL_DATABASE: marmishlag
      MYSQL_ROOT_PASSWORD: password
    volumes:
      # Pour lancer un dump automatiquement au montage du conteneur
      - ./marmishlag.sql:/docker-entrypoint-initdb.d/dump.sql


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1

  wp search-replace 'http://localhost:2345' 'http://141.94.85.207:2345' --skip-columns=guid
  wp option update home 'http://141.94.85.207:2345'
  wp option update siteurl 'http://141.94.85.207:2345'