name: Docker Deploy

on:
  push:
    branches: [main]


jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    - name: Install Docker
      run: apt-get install docker-ce docker-ce-cli containerd.io
           
    - name: Stop Docker
      run: docker-compose down
      
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "Marmishlag/"
          EXCLUDE: "marmishlag.sql"
          
    - name: Start Docker
      run: docker-compose up -d
